# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  APP_PORT: '$(appPort)'
  DB_DEBUG: '$(dbDebug)'
  DB_HOST: '$(dbHost)'
  DB_PASSWORD: '$(dbPassword)'
  DB_PORT: '$(dbPort)'
  DB_USER: '$(dbUser)'
  GIN_MODE: '$(ginMode)'
  REQ_VALIDATOR: '$(reqValidator)'
  MIGRATE: '$(migrate)'
  SEED: '$(seed)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'GlobalContainerRegistry'
        repository: 'packky-tracker-repository'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'