# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  APP_PORT: '$(APP_PORT)'
  DB_DEBUG: '$(DB_DEBUG)'
  DB_HOST: '$(DB_HOST)'
  DB_PASSWORD: '$(DB_PASSWORD)'
  DB_PORT: '$(DB_PORT)'
  DB_USER: '$(DB_USER)'
  GIN_MODE: '$(GIN_MODE)'
  REQ_VALIDATOR: '$(REQ_VALIDATOR)'
  MIGRATE: '$(MIGRATE)'
  SEED: '$(SEED)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'GlobalContainerRegistry'
        repository: 'packky-tracker-repository'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'